
title: turtle developer
email: littleprince0717@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello. Enjoy your time. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://byeongjaelee.github.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: littleprince0717
github_username:  BYEONGJAELEE

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

remote_theme : brianmaierjr/long-haul
